### ISSUE TITLE
建议做个docker镜像

### ISSUE THREAD

**Issue by llongtao** [may-fly/mayfly-go#1]

**Comment by may-fly** [comment]
docker镜像可以加群，有dockerfile，可以自己弄个哈

**Comment by 1ch0** [comment]
@may-fly 有个构建好的 Docker 镜像，大家可以更快速地了解、使用你的项目，我可以试着帮你先做一个，你看看效果。

**Comment by may-fly** [comment]
@1ch0 好的哈

**Comment by may-fly** [comment]
镜像已完成哈  ->  https://objs.gitee.io/mayfly-go-docs/download/
