### ISSUE TITLE
mysql 字段类型为BigInt时 页面id与实际存储不符。

### ISSUE THREAD

**Issue by Zbuter** [may-fly/mayfly-go#11]
![image](https://user-images.githubusercontent.com/40537040/187650379-4ef36b9e-7448-465b-aac0-ce12a59d52bb.png)

数据库值为 1564085134334705665 页面显示为 1564085134334705700

**Comment by may-fly** [comment]
由于 JavaScript 中 Number 类型的自身原因，并不能完全表示 Long 型的数字，在 Long 长度大于17位时会出现精度丢失的问题。
这个我再查查看有没啥其他办法解决

**Comment by rmzf9192** [comment]
在返回界面时将long类型的数字转为字符串

**Comment by may-fly** [comment]
新版问题已修复哈
