### ISSUE TITLE
无法在windows上运行程序

### ISSUE THREAD

**Issue by pbhfcycssjlmm** [may-fly/mayfly-go#15]
下载安装包后，在cmd中运行startup.sh，git bash窗口一闪而过，然后cmd执行完毕。此时使用127.0.0.1:config.yml中配置的server:port访问，提示无法访问此网站。
双击运行mayfly-go.exe也不行，直接就关闭了命令行窗口

**Comment by may-fly** [comment]
大概率是数据库配得有问题，导致访问不了

**Comment by pbhfcycssjlmm** [comment]
确实是这个原因，我数据库地址写错了，建议加个提示信息或者不强依赖现有数据库。
另外，现在登录提示账号密码错误。账号密码用的是readme里面的初始账号 admin/admin123.
