### ISSUE TITLE
windows运行，响应头内容类型错误

### ISSUE THREAD

**Issue by q2316367743** [may-fly/mayfly-go#2]
windows运行，响应头内容类型错误

![image](https://user-images.githubusercontent.com/49052369/185008975-72f33829-b109-40ae-8b5e-0d6de16ef070.png)

导致无法启动

![image](https://user-images.githubusercontent.com/49052369/185009071-f8a56a57-d6f8-4838-93e1-2b33073d03d8.png)

**Comment by may-fly** [comment]
是win10系统吗

**Comment by may-fly** [comment]
是win10系统吗

**Comment by may-fly** [comment]
script type换了个类型，试试看蛤
