### ISSUE TITLE
可用于生产吗，有点担心会不会有漏洞泄露服务器跟数据库的相关信息

### ISSUE THREAD

**Issue by chengjiaxiongkf** [may-fly/mayfly-go#25]
如标题

**Comment by may-fly** [comment]
目前能想到的策略都加了，比如数据库等资源密码用aes加密，登录rsa加密。不过大部分应该都还是用在内网，应该还好

**Comment by QJZX** [comment]
内部防火墙做得好的话，甚至弱密码都没问题，只允许指定的MAC和IP访问指定的网络段，比密码来劲儿多了。

**Comment by QJZX** [comment]
我之前从大佬那里学习到的一个经验是没有密码才是最安全的密码。不应当是基于密码的身份认证。最好是SS H公钥加Unix套接字来进行建立连接。

**Comment by QJZX** [comment]
管理员管理的是各个公钥的授权，而不是直接管理资源的密码。
