### ISSUE TITLE
新增同一服务器上的不同库，会提示数据库实例已存在

### ISSUE THREAD

**Issue by InfraBackend** [may-fly/mayfly-go#27]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/42115674/222617533-a03e231c-5e3a-49ac-b33e-2b7a0aa61be2.png">
mysql，我添加是不同库，只是ip一样，用户是不一样的

**Comment by may-fly** [comment]
目前是ip、port、tag为条件验重，可以先换个标签加，后续调整下

**Comment by InfraBackend** [comment]
还有另一个问题，查询为啥还有限制分页呢，我需要查询导出数据，能不能不限制分页

**Comment by InfraBackend** [comment]
还有另一个问题，查询为啥还有限制分页呢，我需要查询导出数据，能不能不限制分页

**Comment by may-fly** [comment]
可以把系统参数中该参数设为0
<img width="857" alt="image" src="https://user-images.githubusercontent.com/38199635/223034179-130b94f2-193e-46b4-9cad-b25d40a8cd9d.png">

**Comment by InfraBackend** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/42115674/223898692-96a79d4e-33b4-41b5-9549-751fdde7bab3.png">
还有一个问题，就是数据库更新后，在数据操作里，侧边栏里的表不会更新，也没有刷新的地方
