### ISSUE TITLE
redis哨兵模式

### ISSUE THREAD

**Issue by anzhonghui** [may-fly/mayfly-go#35]
哨兵模式请问这样太难正确吗？我的密码是对的，但是日志一直提示我NOAUTH Authentication required.
![image](https://github.com/may-fly/mayfly-go/assets/104904136/e12f70be-c518-4a0e-968b-40100888a32f)

![image](https://github.com/may-fly/mayfly-go/assets/104904136/fa8c64f3-eae6-4f85-ad31-c80cbc2b6458)

**Comment by anzhonghui** [comment]
![image](https://github.com/may-fly/mayfly-go/assets/104904136/d089381b-6845-4453-9473-08fefac45257)
恩恩，正确的

**Comment by may-fly** [comment]
试试只连一个ip可以吗

**Comment by may-fly** [comment]
有办法把密码先去掉吗，测下是密码问题还是连接方式有问题

**Comment by anzhonghui** [comment]
好的，我尝试一下，谢谢
