### ISSUE TITLE
redis哨兵模式，不支持密码认证

### ISSUE THREAD

**Issue by suhanyanyu** [may-fly/mayfly-go#36]
Redis哨兵模式，给哨兵设置有密码，连接时提示以下信息
Redis连接失败: redis: all sentinels specified in configuration are unreachable
取消哨兵密码后则能正常连接

**Comment by may-fly** [comment]
应该是配置写错了哈，mastername为redis-sentinel.conf配置文件里配的哈，不是系统提示里的mastername
