### ISSUE TITLE
redis 集群连接报错

### ISSUE THREAD

**Issue by xiaoWuLab** [may-fly/mayfly-go#4]
集群连接提示 errCode: 400, errMsg: Redis连接失败: got 4 elements in cluster info address, expected 2 or 3 但是在别的客户端该集群可正常连接。

**Comment by may-fly** [comment]
看这字面意思是不是集群的节点数有问题

**Comment by xiaoWuLab** [comment]
我这边用的redis deskTop 直接连接的话 ，是可以正常连接，不过他是只需要一个节点就可以自动识别集群正常连接。但是咱们的客户端提示集群要按照ip:端口，我把有的都加上了，和我们现在跑的程序保持一致了，现在咱们的日志比较简单，看不出来具体的问题在哪里。

**Comment by may-fly** [comment]
该系统也是支持一个的，随便设置一个节点的ip就可以了哈

**Comment by may-fly** [comment]
这问题可以了吗
