### ISSUE TITLE
标签树创建问题

### ISSUE THREAD

**Issue by kanzihuang** [may-fly/mayfly-go#63]
在标签 "ReadOnly/Project" 下创建子标签 DEV, 子标签的 code 路径为 "ReadOnly/ProjectDEV/", 与预期 "ReadOnly/Project/DEV" 不符。

**Comment by may-fly** [comment]
是自己数据库建的吗，如果是程序建的，正常都是/结尾的

**Comment by kanzihuang** [comment]
程序建的标签, code_path 中 Project 和 DEV 之间少一个 "/"。

**Comment by may-fly** [comment]
这个标签ReadOnly/Project的数据库code_path有带末尾有带/吗

**Comment by kanzihuang** [comment]
之前新建的标签结尾没有 "/", 我在数据库里在 code_path 后面手动加上 "/", 新建的子标签就正常了。
